author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /detroit-focus-quarterly-1-1
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
homepage_image: http://192.168.42.5:8000/books/wayne:DFQv1i1_Readux_VirtualVolume/pages/wayne:DFQv1i1_Readux_VirtualPage_1/single-page/
image_size:
  page:
    height: 1000
    width: 757
  small-thumbnail:
    height: 100
    width: 75
  thumbnail:
    height: 300
    width: 227
permalink: pretty
publication_info:
  author: null
  date: '2016'
  editors:
  - Graham Hukill
  tei_xml: tei.xml
  title: Detroit Focus Quarterly 1(1) (January 1982), an annotated digital edition
show_annotation_author: true
source_info:
  author: null
  date: 1982-01
  pdf_url: http://192.168.42.5:8000/books/wayne:DFQv1i1_Readux_VirtualVolume/pdf/
  title: Detroit Focus Quarterly 1(1) (January 1982)
  url: http://192.168.42.5:8000/books/wayne:DFQv1i1_Readux_VirtualVolume/
  via_readux: true
tagline: ', an annotated digital edition'
title: Detroit Focus Quarterly 1(1) (January 1982)
url: http://ghukill.github.io
version: 0.6
